#!/bin/bash
# color

[[ x${1// /} == x || ${#1} > 3 ]] && word=gYw || word=${1}

esc="\e"
id=({1..7}m)
coord=${id[@]}
reset="${esc}[0m"
background=(1\;4{0..7}m)
background_bg=${background[@]}
background_id=${background[@]//1;/}

echo -en "\n            ${background_id// /    }   ${background_bg// /  }   0m    ${coord// /   }\n"

for fg_color in 3{0..7} 1\;3{0..7}; do
    for ((i=0; i<5-${#fg_color}; ++i)); do
          echo -n " "
    done
    echo -en "${fg_color}${esc}[${fg_color}m ${word} "
    i=0
    for bg_color in 4{0..7} 1\;4{0..7} {0..7}; do
        (( i > 16 )) && {
           echo -en "${esc}[${fg_color};${bg_color}m ${word} ${reset}"
        } || echo -en "${esc}[${fg_color};${bg_color}m  ${word}  ${reset}"
        ((++i))
    done
    echo
done
echo

for m in {0..255}; do
    (( (m+1)%32 == 1 )) && echo -ne "\t\t"
    echo -ne "\e[38;5;${m};1m[]\e[0m"
    if (( (m+1)%32 == 0 )); then
          echo -n "   |   "
          for ((n=m-31; n<=m; ++n)); do
                echo -ne "\e[48;5;${n};1m[]\e[0m"
          done
          echo
   fi
done
echo
