#!/bin/bash
# circle_number_left_vector 
 
num=${1:-10}
cur_number=0
((range=num-1))
((loop=num%2+num/2))

circle.number.show()
{
   for ((row=0; row!=num; ++row))
   {
         for ((col=0; col!=num; ++col))
         {
               echo -n "${vec[row*num+col]} "
         }
         echo
   }
}

circle.number.generate()
{
   for ((i=0; i!=loop; ++i))
   {
         ((len=row=i))
         ((k=num-2*i))
         ((up=cur_number))
         ((down=(k == 1)?up:up+k))

         for ((p=0; p<k-2; ++p)); do
               ((vec[(range-len)*num+(++row)]=++down))
         done

         for ((j=0; j!=k; ++j,++len)); do
               ((vec[len*num+i]=++up))
               ((vec[(range-len)*num+range-i]=++down))
         done

         for ((d=0; d<k-2; ++d)); do
               ((vec[i*num+range-i-d-1]=++down))
         done 

         ((cur_number=down))
   }
}

{ circle.number.generate; circle.number.show; } | column -t
