#!/bin/bash
# random_password

str=(/ \` ^ % \* \# @ \( \) \] \[ { } \\ ! $ ? % _ - + = \& \> \< . \~ \, \: \; \' \" \| {a..z} {0..9} {A..Z})
size=${1:-8}
len=${#str[@]}

for ((i=0; i!=size; ++i)); do
      echo -n "${str[RANDOM%len]}"
done 
echo
